# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61ebded71f5ddc12c4fa05c0ad2c105c"
name = "EZ Alerts"
handle = "ez-alerts"
application_url = "https://fluid-relate-publishers-lauren.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vytasstore2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fluid-relate-publishers-lauren.trycloudflare.com/auth/callback",
  "https://fluid-relate-publishers-lauren.trycloudflare.com/auth/shopify/callback",
  "https://fluid-relate-publishers-lauren.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
